# fly.toml app configuration file generated for pf-back on 2023-07-05T13:10:55-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pf-back"
primary_region = "scl"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
